# Generated by Django 2.1.7 on 2019-03-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodsinfo',
            table='goodsinfo',
        ),
        migrations.AlterModelTable(
            name='typeinfo',
            table='typeinfo',
        ),
    ]
