# Generated by Django 2.1.7 on 2019-03-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20190308_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeinfo',
            options={'verbose_name': 'TypeInfo', 'verbose_name_plural': 'TypeInfo'},
        ),
        migrations.AlterField(
            model_name='typeinfo',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='IfDelete'),
        ),
        migrations.AlterField(
            model_name='typeinfo',
            name='ttitle',
            field=models.CharField(max_length=20, verbose_name='TypeName'),
        ),
    ]
