# Generated by Django 2.1.7 on 2019-03-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0002_auto_20190307_2150'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartinfo',
            table='cartinfo',
        ),
    ]
