# Generated by Django 2.1.7 on 2019-03-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20190308_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'userinfo', 'verbose_name_plural': 'userinfo'},
        ),
    ]
